version: '3.9'

services:
  cockroach_1:
    image: cockroachdb/cockroach:latest
    ports:
      - "8080:8080"
    command:
      - start
      - --insecure
      - --join=cockroach_1,cockroach_2

  cockroach_2:
    image: cockroachdb/cockroach:latest
    ports:
      - "8081:8080"
    command:
      - start
      - --insecure
      - --join=cockroach_1,cockroach_2